# Generated by Django 3.1.1 on 2021-04-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_profile",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("followed", models.BooleanField(default=False)),
                ("ignore", models.BooleanField(default=False)),
                ("must_follow", models.BooleanField(default=False)),
                ("must_like", models.BooleanField(default=False)),
                ("must_rt", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                ("retweet_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tweet_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("text", models.CharField(max_length=500)),
                ("retweeted", models.BooleanField(default=False)),
                ("liked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="twitter_data.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=5)),
                ("ignore_rt", models.BooleanField(default=False)),
                ("only_links", models.BooleanField(default=False)),
                ("must_like", models.BooleanField(default=False)),
                ("must_rt", models.BooleanField(default=False)),
                ("keywords", models.ManyToManyField(to="twitter_data.Keyword")),
            ],
        ),
    ]
