# Generated by Django 3.1.1 on 2021-04-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
