# Generated by Django 3.1.1 on 2021-04-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_data", "0002_user_ignore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="tweet_id",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_profile",
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
