# Generated by Django 3.1.1 on 2021-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_data", "0002_user_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("private_key", models.TextField()),
            ],
        ),
    ]
