# Generated by Django 3.1.1 on 2021-09-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_data", "0003_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="replied",
            field=models.BooleanField(default=False),
        ),
    ]
