# Generated by Django 3.1.1 on 2021-04-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_data", "0003_auto_20210403_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="retweet_count",
            field=models.IntegerField(default=0),
        ),
    ]
