# Generated by Django 3.1.1 on 2021-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_data", "0004_auto_20210408_2254"),
    ]

    operations = [
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("value", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.CharField(max_length=500),
        ),
    ]
